map_update_interval: 2.0
maxUrange: 50.0
sigma: 0.05
kernelSize: 1
lstep: 0.05
astep: 0.05
iterations: 5
lsigma: 0.075
ogain: 3.0
lskip: 0
minimumScore: 0.005
srr: 0.01
srt: 0.02
str: 0.01
stt: 0.02
linearUpdate: 0.01
angularUpdate: 0.01
temporalUpdate: 0.5
resampleThreshold: 0.5
particles: 30
xmin: -5.0
ymin: -5.0
xmax: 5.0
ymax: 5.0
delta: 0.1
llsamplerange: 0.01
llsamplestep: 0.01
lasamplerange: 0.005
lasamplestep: 0.005
